const productsCMS =
{   
    strain_main_text:'Strain Type',
    strain_types:[
        {name:'Sativa'},
        {name:'Hybrid'},
        {name:'Indica'},
        {name:'CBD'},
        {name:'Sativa'},
        {name:'Hybrid'},
        {name:'Indica'},
        {name:'CBD'},
        {name:'Sativa'},
        {name:'Hybrid'},
        {name:'Indica'},
        {name:'CBD'},
        {name:'Sativa'},
        {name:'Hybrid'},
        {name:'Indica'},
        {name:'CBD'},
        {name:'Sativa'},
        {name:'Hybrid'},
        {name:'Indica'},
        {name:'CBD'},
    ],
    brand_main_text:'Brands',
    brands:[
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
        {name:'Tata'},
        {name:'Toyota'},
        {name:'BMW'},
        {name:'Mercedes'},
    ],
    brand_button_text:'Show More',
    potency_main_text:'The Potency',
    size_main_text:'Size',
    flower_main_text:'Flower Type',
    flowers:[
        {name:'Rse'},
        {name:'Bbqe'},
        {name:'Abcd'},
        {name:'Wow'},
    ],
    effects_main_text:'Effects',
    flavors_main_text:'Flavors and Aromas',
    offers_main_text:'Special Offers',
    offers:[
        {name:'Calm'},
        {name:'Clear Mind'},
        {name:'Creative'},
        {name:'Energetic'},
        {name:'Focused'},
        {name:'Happy'},
        {name:'Calm'},
        {name:'Clear Mind'},
        {name:'Creative'},
        {name:'Energetic'},
        {name:'Focused'},
        {name:'Happy'},
        {name:'Calm'},
        {name:'Clear Mind'},
        {name:'Creative'},
        {name:'Energetic'},
        {name:'Focused'},
        {name:'Happy'},
        {name:'Calm'},
        {name:'Clear Mind'},
        {name:'Creative'},
        {name:'Energetic'},
        {name:'Focused'},
        {name:'Happy'},
    ],
    weights:[
        {quantity:'3.5g'},
        {quantity:'5g'},
        {quantity:'7g'},
        {quantity:'7.5g'},
        {quantity:'12g'},
        {quantity:'15g'},
    ],
    site_sub_text:'Show More',
    
    filter_button:[
        {text:'Flowers'},
        {text:'Curbside'},
        {text:'Product Type'},
    ],
    product_button:'ADD',
    product:[
        {
         id:0,
         img_url:'../../images/prod_img_1.png',
         upper_text:'Test Provisioning',
         name:'Memory Prepackaged Flower',
         price_text:'Now',
         new_price:'$79',
         old_price:'$99',
         weight:'1 oz',
         left_info:'Sativa',
         right_info:'THC 23.26%',
         discount:'20% OFF',
        },
        {
            id:1,
            img_url:'../../images/prod_img_1.png',
            upper_text:'Test Provisioning',
            name:'Memory Loss Prepackaged Flower',
            price_text:'Now',
            new_price:'$79',
            old_price:'$99',
            weight:'1 oz',
            left_info:'Sativa',
            right_info:'THC 23.26%',
            discount:'20% OFF',
           },
           {
            id:2,
            img_url:'../../images/prod_img_1.png',
            upper_text:'Test Provisioning',
            name:'Memory Loss Prepackaged Flower',
            price_text:'Now',
            new_price:'$79',
            old_price:'$99',
            weight:'1 oz',
            left_info:'Sativa',
            right_info:'THC 23.26%',
            discount:'20% OFF',
           },
           {
            id:3,
            img_url:'../../images/prod_img_1.png',
            upper_text:'Test Provisioning',
            name:'Memory Loss Prepackaged Flower',
            price_text:'Now',
            new_price:'$79',
            old_price:'$99',
            weight:'1 oz',
            left_info:'Sativa',
            right_info:'THC 23.26%',
            discount:'20% OFF',
           },
           {
            id:4,
            img_url:'../../images/prod_img_1.png',
            upper_text:'Test Provisioning',
            name:'Memory Loss Prepackaged Flower',
            price_text:'Now',
            new_price:'$79',
            old_price:'$99',
            weight:'1 oz',
            left_info:'Sativa',
            right_info:'THC 23.26%',
            discount:'20% OFF',
           },
    ],
    
}
export default productsCMS